In [ ]:
# face_recognition from image
import os
import cv2
from keras.models import load_model
import numpy as np

def facePredict(img_path, h5_path):
    model = load_model(h5_path)
    img = cv2.imread(img_path)
    img = cv2.resize(img, (128, 128))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = img.reshape((1, 1, 128, 128))
    img = img.astype('float32')
    img = img/255.0
    faceProb = model.predict(img)/max(model.predict(img)[0])
    faceLabel = np.argmax(model.predict(img))
    return faceProb, faceLabel


#print(facePredict("E:/testtt/n003554/1575082734424.jpg", "D:/桌面/FaceFinal.h5"))
#faceProb, faceLabel = facePredict("E:/testttt/276.jpg", "D:/桌面/FaceFinal.h5")
faceProb, faceLabel = facePredict("jj.jpg","D:/桌面/FaceFinal.h5")
print(faceProb)
print(faceLabel)

In [ ]:
import os
import numpy 
import librosa
import numpy as np
from keras.models import load_model
import python_speech_features as psf



#simple processing of the input signal
def getWavFeatures(wavPath):
    signal,rate = librosa.load(wavPath, sr=16000)
    if len(signal) >= 3 * 16000:
        signal = signal[0:int(3 * 16000)]
    else:
        signal = signal.tolist()
        for j in range(3 * 16000 - len(signal)):
            signal.append(0)
        signal = np.array(signal)
    feat = psf.logfbank(signal, samplerate=16000, nfilt=64)
    feat1 = psf.delta(feat, 1)
    feat2 = psf.delta(feat, 2)
    feat = feat.T[:, :, np.newaxis]
    feat1 = feat1.T[:, :, np.newaxis]
    feat2 = feat2.T[:, :, np.newaxis]
    fBank = np.concatenate((feat, feat1, feat2), axis=2)
    a = []
    a.append(fBank)
    fBank = np.array(a)
    # print(fBank.shape)
    return fBank

def voicePredict(wav,h5):
    feat = getWavFeatures(wav)
    model = load_model(h5)
    voiceProb = model.predict(feat)
    voiceLabel = np.argmax(voiceProb[0])
    return voiceProb, voiceLabel
    
voiceProb, voiceLabel = voicePredict("E:data_aishell/wav/train/S0002/BAC009S0002W0130.wav", "D:/桌面/voice 9546.h5")

In [ ]:
combine = np.add(faceProb,voiceProb)
#combine = faceProb*voiceProb
print(combine)
print(np.argmax(combine[0]))

In [ ]:
#gray
#put all the images in one list and crop out the faces
def greyScaleAndSave(sourcePath,objectPath,*format):
    try:
        # read the images
        resultArray=readAllImg(sourcePath,*format)

        #crop out the faces are save into a new path

        count = 0
        face_cascade = cv2.CascadeClassifier("D:\Anaconda\envs\py36\Lib\site-packages\cv2\data\haarcascade_frontalface_default.xml")
        #while count < 20:
        for i in resultArray:

            #if type(resultArray[count]) != str: 
            if count == 20:
                break
            elif type(i) != str:

                #gray = cv2.cvtColor(resultArray[count], cv2.COLOR_BGR2GRAY)
                gray = cv2.cvtColor(i, cv2.COLOR_BGR2GRAY)
                faces = face_cascade.detectMultiScale(gray, 1.3, 5)
                for (x, y, w, h) in faces:
                    # number the files use it as the file name
                    fileName = str(count)
                    #print(fileName)

                    f = cv2.resize(gray[y:(y + h), x:(x + w)], (200, 200))
                    cv2.imwrite(objectPath+os.sep+'%s.jpg' % fileName, f)
                    count += 1


    except IOError:
        print ("Error, the file may not be found")

    else:
        #print ('Successfully add '+str(count-1)+' Faces to Destination ' + objectPath)
        pass
if __name__ == '__main__':
  L = []
  path = 'E:/FR/vggface2_test/testt/'
  
  try:
    os.makedirs("E:/testttt/")
  except:
    pass

  for i in sorted(os.listdir(path)): 
    L.append(i)
    path = os.path.join("E:/testttt/" + i)
    os.makedirs(path)
  for i in L:
    greyScaleAndSave("E:/FR/vggface2_test/testt/"+i,'E:/testttt/'+i,'.jpg','.JPG','png','PNG')


In [ ]:
import os
import cv2
from keras.models import load_model
import numpy as np

def facePredict(img_path, h5_path):
    model = load_model(h5_path)
    img = cv2.imread(img_path)
    img = cv2.resize(img, (128, 128))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = img.reshape((1, 1, 128, 128))
    img = img.astype('float32')
    img = img/255.0
    faceProb = model.predict(img)/max(model.predict(img)[0])
    faceLabel = np.argmax(model.predict(img))
    return faceProb, faceLabel
bigArray = np.zeros((200,20,1,200))
path = "faceTestt/"
countt = 0
for i in sorted(os.listdir(path)): 
  count = 0
  for j in sorted(os.listdir(path+i)):
    subPath = path+i+"/"+j
    faceProb, faceLabel = facePredict(subPath, "FaceFinal.h5")
    bigArray[countt][count] = faceProb
    count += 1
  countt += 1
np.save("a.npy",bigArray)

In [ ]:
import numpy as np
fp = np.memmap("D:/桌面/test.dat",dtype='float32',mode='w+',shape=(200,20,1,200))


In [ ]:
np.shape(fp)

In [ ]:
import numpy as np
fp = np.memmap("D:/桌面/test.dat",mode="r+",shape=(200,20,1,200))
np.shape(fp)

In [ ]:
fp[0][0] = faceProb

In [ ]:
fp[0][0]

In [ ]:
np.shape(fp)

In [ ]:
del fp

In [ ]:
fp

In [ ]:
import os 
import shutil
os.makedirs("E:/VoiceTest/")
L = []
path = "E:/voice/"
for i in sorted(os.listdir(path)): 
  L.append(i)
  newPath = os.path.join("E:/VoiceTest/" + i)
  #os.makedirs(newPath)
for i in L:
  count = 0
  os.makedirs("E:/VoiceTest/"+i)
  for j in sorted(os.listdir("E:/voice/" + i))[:20]:
    shutil.copyfile("E:/voice/"+i+"/"+j,"E:/VoiceTest/"+i+"/"+str(count)+".wav") 
    count += 1


In [ ]:
import os
import librosa
import numpy as np
from keras.models import load_model
import python_speech_features as psf



#simple processing of the input signal
def getWavFeatures(wavPath):
    signal,rate = librosa.load(wavPath, sr=16000)
    if len(signal) >= 3 * 16000:
        signal = signal[0:int(3 * 16000)]
    else:
        signal = signal.tolist()
        for j in range(3 * 16000 - len(signal)):
            signal.append(0)
        signal = np.array(signal)
    feat = psf.logfbank(signal, samplerate=16000, nfilt=64)
    feat1 = psf.delta(feat, 1)
    feat2 = psf.delta(feat, 2)
    feat = feat.T[:, :, np.newaxis]
    feat1 = feat1.T[:, :, np.newaxis]
    feat2 = feat2.T[:, :, np.newaxis]
    fBank = np.concatenate((feat, feat1, feat2), axis=2)
    a = []
    a.append(fBank)
    fBank = np.array(a)
    # print(fBank.shape)
    return fBank

def voicePredict(wav,h5):
    feat = getWavFeatures(wav)
    model = load_model(h5)
    voiceProb = model.predict(feat)
    voiceLabel = np.argmax(voiceProb[0])
    return voiceProb, voiceLabel
#voiceProb, voiceLabel = voicePredict("testt/S0002/0.wav","/content/drive/My Drive/Colab Notebooks/voice 9546.h5")
#print(voiceProb)

#bigArray = np.zeros((200,20,1,200))
fp = np.memmap("E:/testt.dat",mode = "w+",shape=(200,20,1,200))
path = "E:/VoiceTest/"
countt = 0
try:
  for i in sorted(os.listdir(path)): 
    count = 0
    for j in sorted(os.listdir(path+i)):
      subPath = path+i+"/"+j
      faceProb, faceLabel = voicePredict(subPath, "D:/桌面/voice 9546.h5")
      fp[countt][count] = faceProb
      count += 1
    countt += 1
    print(countt)
  #np.save("b.npy",bigArray)
  del fp
except Exception as err:
  print(err)

In [ ]:
import tables 
import numpy as np
print(np.shape(faceProb))

In [ ]:
hdf5_path = "test_data.hdf5"
hdf5_file = tables.open_file(hdf5_path, mode='w')
filters = tables.Filters(complevel=5, complib='blosc')

In [ ]:
filters = tables.Filters(complevel=5, complib='blosc')
earray = hdf5_file.create_earray(
	hdf5_file.root,
	'data', # 数据名称，之后需要通过它来访问数据
	tables.Atom.from_dtype(bigArray.dtype), # 设定数据格式（和data1格式相同）
	shape=(0,20,1,200), # 第一维的 0 表示数据可沿行扩展
	filters=filters,
	expectedrows=800000 # 完整数据大约规模，可以帮助程序提高时空利用效率
)
# 将 data1 添加进 earray
earray.append(bigArray)
# 写完之后记得关闭文件
hdf5_file.close()


In [ ]:
hdf5_path = "test_data.hdf5"
hdf5_file = tables.open_file(hdf5_path, mode='r')
# 数据名称为 'data'，我们可以通过 .root.data 访问到它
hdf5_data = hdf5_file.root.data
print(hdf5_data.shape) # (1000, 4096)
# 像在内存中一样自由读取数据切片！
print(hdf5_data[:10].shape)
hdf5_file.close()

In [ ]:
hdf5_file.close()

In [1]:
import os
import cv2
from keras.models import load_model
import numpy as np

def facePredict(img_path, h5_path):
    model = load_model(h5_path)
    img = cv2.imread(img_path)
    img = cv2.resize(img, (128, 128))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = img.reshape((1, 1, 128, 128))
    img = img.astype('float32')
    img = img/255.0
    faceProb = model.predict(img)
    faceLabel = np.argmax(model.predict(img))
    return faceProb, faceLabel
bigArray = np.zeros((20,1,200))
#fp = np.memmap("test.dat",mode = "w+",shape=(200,20,1,200))
path = "E:/testttt/n000009"
count = 0
try:
    for j in sorted(os.listdir(path)):
        subPath = path+"/"+j
        faceProb, faceLabel = facePredict(subPath, "D:/桌面/FaceFinal.h5")
        bigArray[count] = faceProb
        count += 1
        print(count)
    #del fp
    #np.save("a.npy",bigArray)
except Exception as err:
  print(err)
print(bigArray)

Using TensorFlow backend.


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
[[[0. 1. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]]

 ...

 [[0. 1. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]]]


In [2]:
bigArray = np.reshape(bigArray,(1,20,1,200))

In [3]:
print(np.shape(bigArray))

(1, 20, 1, 200)


In [5]:
import tables
hdf5_path = "test_data.hdf5"
# 注意这里 mode 应为 'a'
hdf5_file = tables.open_file(hdf5_path, mode='a')
hdf5_data = hdf5_file.root.data
print(hdf5_data.shape) # (1000, 4096)
hdf5_data.append(bigArray)
hdf5_file.close()


(1, 20, 1, 200)


In [1]:
hdf5_file = tables.open_file(hdf5_path, mode='r')
print(hdf5_file.root.data.shape) # (2000, 4096)
hdf5_file.close()

NameError: name 'tables' is not defined

In [ ]:
import os
import cv2
from keras.models import load_model
import numpy as np
import gc

def facePredict(img_path, h5_path):
    model = load_model(h5_path)
    img = cv2.imread(img_path)
    img = cv2.resize(img, (128, 128))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = img.reshape((1, 1, 128, 128))
    img = img.astype('float32')
    img = img/255.0
    faceProb = model.predict(img)/max(model.predict(img)[0])
    faceLabel = np.argmax(model.predict(img))
    return faceProb, faceLabel
bigArray = np.zeros((20,1,200))
#fp = np.memmap("test.dat",mode = "w+",shape=(200,20,1,200))


import tables
hdf5_path = "test_data.hdf5"
hdf5_file = tables.open_file(hdf5_path, mode='w')
filters = tables.Filters(complevel=5, complib='blosc')

filters = tables.Filters(complevel=5, complib='blosc')
earray = hdf5_file.create_earray(
	hdf5_file.root,
	'data', # 数据名称，之后需要通过它来访问数据
	tables.Atom.from_dtype(bigArray.dtype), # 设定数据格式（和data1格式相同）
	shape=(0,20,1,200), # 第一维的 0 表示数据可沿行扩展
	filters=filters,
	expectedrows=800000 # 完整数据大约规模，可以帮助程序提高时空利用效率
)
hdf5_file.close()

path = "E:/testttt/"
countt = 0
try:
    for i in sorted(os.listdir(path)): 
        count = 0
        for j in sorted(os.listdir(path+i)):
            subPath = path+i+"/"+j
            faceProb, faceLabel = facePredict(subPath, "D:/桌面/FaceFinal.h5")
            bigArray[count] = faceProb
            count += 1
            print("small"+str(count))
        bigArray = np.reshape(bigArray,(1,20,1,200))
        hdf5_path = "test_data.hdf5"
        # 注意这里 mode 应为 'a'
        hdf5_file = tables.open_file(hdf5_path, mode='a')
        hdf5_data = hdf5_file.root.data
        hdf5_data.append(bigArray)
        hdf5_file.close()
        countt += 1
        del bigArray
        gc.collect()
        bigArray = np.zeros((20,1,200))
        print("big"+str(countt))
    #np.save("a.npy",bigArray)
except Exception as err:
  print(err)

Using TensorFlow backend.


small1
small2
small3
small4
small5
small6
small7
small8
small9
small10
small11
small12
small13
small14
small15
small16
small17
small18
small19
small20
big1
small1
small2
small3
small4
small5
small6
small7
small8
small9


In [ ]:

import os
import cv2
from keras.models import load_model
import numpy as np
import gc

def facePredict(img_path, h5_path):
    model = load_model(h5_path)
    img = cv2.imread(img_path)
    img = cv2.resize(img, (128, 128))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = img.reshape((1, 1, 128, 128))
    img = img.astype('float32')
    img = img/255.0
    faceProb = model.predict(img)/max(model.predict(img)[0])
    faceLabel = np.argmax(model.predict(img))
    del img
    gc.collect()
    return faceProb, faceLabel

#fp = np.memmap("test.dat",mode = "w+",shape=(200,20,1,200))


import os
import numpy 
import librosa
import numpy as np
from keras.models import load_model
import python_speech_features as psf



#simple processing of the input signal
def getWavFeatures(wavPath):
    signal,rate = librosa.load(wavPath, sr=16000)
    if len(signal) >= 3 * 16000:
        signal = signal[0:int(3 * 16000)]
    else:
        signal = signal.tolist()
        for j in range(3 * 16000 - len(signal)):
            signal.append(0)
        signal = np.array(signal)
    feat = psf.logfbank(signal, samplerate=16000, nfilt=64)
    feat1 = psf.delta(feat, 1)
    feat2 = psf.delta(feat, 2)
    feat = feat.T[:, :, np.newaxis]
    feat1 = feat1.T[:, :, np.newaxis]
    feat2 = feat2.T[:, :, np.newaxis]
    fBank = np.concatenate((feat, feat1, feat2), axis=2)
    a = []
    a.append(fBank)
    fBank = np.array(a)
    # print(fBank.shape)
    return fBank

def voicePredict(wav,h5):
    feat = getWavFeatures(wav)
    model = load_model(h5)
    voiceProb = model.predict(feat)
    voiceLabel = np.argmax(voiceProb[0])
    return voiceProb, voiceLabel

L=[]
facePath = "E:/testttt/n000001/"
voicePath = "E:/VoiceTest/S0002/"
faceModel = "D:/桌面/FaceFinal.h5"
faceSubPath = sorted(os.listdir(facePath))
voiceModel = "D:/桌面/voice 9546.h5"
voiceSubPath = sorted(os.listdir(voicePath))

print(faceSubPath)
for i in range(20):
    #faceArray = np.zeros(20,1,200)
    #voiceArray = np.zeros(20,1,200)
    print(facePath + faceSubPath[i])
    faceProb, faceLabel = facePredict(facePath + faceSubPath[i],faceModel)
    voiceProb, voiceLabrl = voicePredict(voicePath + voiceSubPath[i],voiceModel)
    faceProb = faceProb/max(faceProb[0])
    voiceProb = voiceProb/max(voiceProb[0])
    com = np.add(faceProb,voiceProb)
    #print(np.argmax(com))
    L.append(np.argmax(com))
print(L)


Using TensorFlow backend.


['0.jpg', '1.jpg', '10.jpg', '11.jpg', '12.jpg', '13.jpg', '14.jpg', '15.jpg', '16.jpg', '17.jpg', '18.jpg', '19.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg']
E:/testttt/n000001/0.jpg
E:/testttt/n000001/1.jpg
E:/testttt/n000001/10.jpg
E:/testttt/n000001/11.jpg
E:/testttt/n000001/12.jpg
E:/testttt/n000001/13.jpg
E:/testttt/n000001/14.jpg
E:/testttt/n000001/15.jpg
E:/testttt/n000001/16.jpg


In [ ]:
import os
import cv2
from keras.models import load_model
import numpy as np
import gc

def facePredict(img_path, h5_path):
    model = load_model(h5_path)
    img = cv2.imread(img_path)
    img = cv2.resize(img, (128, 128))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = img.reshape((1, 1, 128, 128))
    img = img.astype('float32')
    img = img/255.0
    faceProb = model.predict(img)/max(model.predict(img)[0])
    faceLabel = np.argmax(model.predict(img))
    del img
    gc.collect()
    return faceProb, faceLabel

#fp = np.memmap("test.dat",mode = "w+",shape=(200,20,1,200))


import os
import numpy 
import librosa
import numpy as np
from keras.models import load_model
import python_speech_features as psf



#simple processing of the input signal
def getWavFeatures(wavPath):
    signal,rate = librosa.load(wavPath, sr=16000)
    if len(signal) >= 3 * 16000:
        signal = signal[0:int(3 * 16000)]
    else:
        signal = signal.tolist()
        for j in range(3 * 16000 - len(signal)):
            signal.append(0)
        signal = np.array(signal)
    feat = psf.logfbank(signal, samplerate=16000, nfilt=64)
    feat1 = psf.delta(feat, 1)
    feat2 = psf.delta(feat, 2)
    feat = feat.T[:, :, np.newaxis]
    feat1 = feat1.T[:, :, np.newaxis]
    feat2 = feat2.T[:, :, np.newaxis]
    fBank = np.concatenate((feat, feat1, feat2), axis=2)
    a = []
    a.append(fBank)
    fBank = np.array(a)
    # print(fBank.shape)
    return fBank

def voicePredict(wav,h5):
    feat = getWavFeatures(wav)
    model = load_model(h5)
    voiceProb = model.predict(feat)
    voiceLabel = np.argmax(voiceProb[0])
    return voiceProb, voiceLabel

facePath = "E:/testttt/"
voicePath = "E:/VoiceTest/"
faceSubPath = sorted(os.listdir(facePath))
voiceSubPath = sorted(os.listdir(voicePath))
faceModel = "D:/桌面/FaceFinal.h5"
#faceSubSubPath = sorted(os.listdir(facePath))
voiceModel = "D:/桌面/voice 9546.h5"
#voiceSubSubPath = sorted(os.listdir(voicePath))

#print(faceSubPath)
for i in range(200):
  print("i" + str(i))
  faceSubSubPath = sorted(os.listdir(facePath + faceSubPath[i]+"/"))
  voiceSubSubPath = sorted(os.listdir(voicePath + voiceSubPath[i]+"/"))
  count  = 0
  for j in range(20):
      print("j" + str(j))
      #faceArray = np.zeros(20,1,200)
      #voiceArray = np.zeros(20,1,200)
      #print(facePath + faceSubPath[i])
      #print(facePath + faceSubPath[i] +"/" faceSubSubPath[j] ,faceModel)
      faceProb, faceLabel = facePredict(facePath + faceSubPath[i] +"/"+ faceSubSubPath[j] ,faceModel)
      voiceProb, voiceLabrl = voicePredict(voicePath + voiceSubPath[i] +"/"+ voiceSubSubPath[j],voiceModel)
      faceProb = faceProb/max(faceProb[0])
      voiceProb = voiceProb/max(voiceProb[0])
      com = np.add(faceProb,voiceProb)
      result = np.argmax(com)
      if result == i:
        count += 1

  f = open("record.txt","a")
  f.write("count")
  f.close()  


Using TensorFlow backend.


i0
j0
j1
j2
j3
j4
j5
j6
j7
j8
